// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livingroom.proto

package com.house.objects;

public interface AirConditioningOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intelligentHouse.AirConditioning)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bool turn = 1;</code>
   * @return Whether the turn field is set.
   */
  boolean hasTurn();
  /**
   * <code>required bool turn = 1;</code>
   * @return The turn.
   */
  boolean getTurn();

  /**
   * <code>required .intelligentHouse.AirConditioning.Status status = 2;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>required .intelligentHouse.AirConditioning.Status status = 2;</code>
   * @return The status.
   */
  com.house.objects.AirConditioning.Status getStatus();

  /**
   * <code>required int32 setting_temperature = 3;</code>
   * @return Whether the settingTemperature field is set.
   */
  boolean hasSettingTemperature();
  /**
   * <code>required int32 setting_temperature = 3;</code>
   * @return The settingTemperature.
   */
  int getSettingTemperature();
}
