// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livingroom.proto

package com.house.objects;

public interface AirConditioningInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intelligentHouse.AirConditioningInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string porta = 3;</code>
   * @return The porta.
   */
  java.lang.String getPorta();
  /**
   * <code>string porta = 3;</code>
   * @return The bytes for porta.
   */
  com.google.protobuf.ByteString
      getPortaBytes();
}
