// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livingroom.proto

package com.house.objects;

public interface TempSensorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intelligentHouse.TempSensor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   * @return The temperature.
   */
  int getTemperature();
}
