// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livingroom.proto

package com.house.objects;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intelligentHouse.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string comando = 1;</code>
   * @return The comando.
   */
  java.lang.String getComando();
  /**
   * <code>string comando = 1;</code>
   * @return The bytes for comando.
   */
  com.google.protobuf.ByteString
      getComandoBytes();
}
